### ISSUE TITLE
JSHint validation issue

### ISSUE THREAD

**Issue by swapnilk** [wilk/Ext.ux.Deferred#11]
JSHint validator is unhappy with promise method -
 
change -

    promise: function () {
        var me = this;

        if (me.internalPromise instanceof Ext.ux.Promise) return me.internalPromise;
        else return me.internalPromise = Ext.create('Ext.ux.Promise'); //JSHint validator complaints
    }

to 

    promise: function () {
        var me = this;

        if (me.internalPromise instanceof Ext.ux.Promise) {
            return me.internalPromise;
        }
        else {
            me.internalPromise = Ext.create('Ext.ux.Promise');
            return me.internalPromise;
        }
    }

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
