### ISSUE TITLE
Chaining of asynchronous functions is not working!

### ISSUE THREAD

**Issue by swapnilk** [wilk/Ext.ux.Deferred#12]
I'm trying to do as follows:

//task1,task2, task3 are functions

//task1 returns promise
task1()
//task2 returns promise
.then(task2)
.then(task3)

I want to execute task 3 only when the promise of task 2 is resolved. This doesn't work. 

As soon as promise for task1 is resolved code executes task2 and task3. Can you look into this bug?

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
