### ISSUE TITLE
Sequential promises

### ISSUE THREAD

**Issue by th3nu11** [wilk/Ext.ux.Deferred#15]
function aSync1(val) {
    var dfd = Ext.create('Ext.ux.Deferred'), task = setInterval(function() {
        console.log('async:' + val);
        dfd.resolve(val);

```
    clearInterval(task);
}, 1000);

return dfd.promise();
```

};

```
var promise = null;
for (var i = 0; i < 10; i++) {
    if (promise) {
        promise = promise.then(function() {
            return aSync1(i);
        });
    } else {
        promise = aSync1(i);
    }
}
promise.then(function() {
    console.log('complete', arguments)
});
```

//expected results 
async: 0
async: 1
async: 2
...
async: 9
complete

//true result
async: 0
complete

**Comment by wilk** [comment]
This project is no longer mainteined. Sorry.
